apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  labels:
    release: stable
spec:
  project: default
  source:
    repoURL: {{ .Values.application.repo }}
    targetRevision: {{ .Values.application.targetRevision }}
    path: {{ .Values.application.path }}
    helm:
      valueFiles: {{ .Values.application.envValues }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.application.name }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    validate: true
