---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sock-shop-front-end.name" . }}-int
  labels:
    {{- include "sock-shop-front-end.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 8079
  selector:
    name: front-end
