---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sock-shop-front-end.name" . }}
  labels:
    {{- include "sock-shop-front-end.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
  selector:
    name: front-end
  loadBalancerSourceRanges:
    - 205.207.104.229/32
    - 205.207.104.237/32
    - 205.207.104.236/32
