apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sock-shop-front-end
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  description: Example Project
  destinations:
  - namespace: sock-shop-front-end*
    server: https://kubernetes.default.svc
  - namespace: argo
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
