# Default values for sock-shop-front-end.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: index.docker.io/weaveworksdemos/front-end
  tag: 0.3.12
  pullPolicy: IfNotPresent

argocd-chart:
  enabled: false
  environment_values: values.yaml
